/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.shopmium.appsflyer;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import com.appsflyer.AppsFlyerLib;

@Kroll.module(name="Android", id="com.shopmium.appsflyer")
public class AndroidModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "AndroidModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public AndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods

	@Kroll.method
	public void startTracker(String appsFlyerDevKey) {
		Log.d(TAG, "[DEBUG] AppsFlyer > startTracker: appsFlyerDevKey:" + appsFlyerDevKey);
		AppsFlyerLib.setAppsFlyerKey(appsFlyerDevKey);
	}

	@Kroll.method
	public void setInstallId(String installId) {
		AppsFlyerLib.setAppUserId(installId);
	}

	@Kroll.method
	public void trackAppLaunch() {
		Log.d(TAG, "[DEBUG] AppsFlyer > TrackLAppLaunch: customerUserID:" + AppsFlyerLib.getAppUserId());
		TiApplication appContext = TiApplication.getInstance();
		AppsFlyerLib.sendTracking(appContext);
	}

	@Kroll.method
	public void trackEvent(String eventName, String eventValue) {
		TiApplication appContext = TiApplication.getInstance();
		AppsFlyerLib.sendTrackingWithEvent(appContext, eventName, eventValue);
	}
}

